### ISSUE TITLE
Windows 7, 8, 8.1 crashes

### ISSUE THREAD

**Issue by jukfiuune** [p2r3/spplice#11]
Hi! I downloaded your launcher, but it crashed on Windows 8.1. After a bit of digging I found out that NeutralinoJS doesn't support Windows 7 - 8.1. If it is possible your mods, like the Cappy one, to be installed manually? If so it would be a great idea for people like me to have an option for Spplice only mods to be installed manually. Have a great day!

NeutralinoJS Windows 7 - 8.1 issue - https://github.com/neutralinojs/neutralinojs/issues/486

**Comment by p2r3** [comment]
Spplice exists specifically to prevent people from attempting to manually install mods. Prior to developing Spplice, we had complaints of people not being able to remove the mods they've installed. It's not intuitive for the end user. We will not be providing manual downloads.

Regardless, the Neutralino issue you have just brought up mentions support for Windows 7 and upwards. I have seen users run Spplice on Windows 7 or 8 before, but immediate crashes are of least concern. What you're most likely experiencing is an unrelated issue where Neutralino doesn't support Unicode characters in the Windows username.

Even if this issue is fixed on your end, Spplice itself does not support anything below Windows 10. In order to simplify cross-platform code, `curl` and `tar` are required for downloading and extracting the packages, which only UNIX-based systems and Windows 10 typically have by default. You can try to find these binaries and force them into system32, but keep in mind that this does not solicit official support.

Windows 7 and 8 have reached end of support years ago. Windows 7 may not bundle PowerShell, which Spplice occasionally relies on. Windows 8.1, while still supported by Microsoft, does not comply with the same standards that Windows 10 has. We are not fixing compatibility issues on a versioning scale.
