### ISSUE TITLE
Stuck on "Failed to create link, copying instead"

### ISSUE THREAD

**Issue by kirjorjos** [p2r3/spplice#18]
I downloaded the Linux AppImage, attempted to launch several mods, and every one gets stuck at the same point.  I left it alone for 10 hours while I was out today to make sure I wasn't just being impatient and it didn't really help.
```
Beginning installation of package "reverse"

Reading config.json
Checking for common Linux/OSX Steam paths
Home directory is "/home/kirjorjos"
Using Steam path "/home/kirjorjos/.steam/steam"
Checking libraryfolders.vdf for AppID 620
Using Portal 2 path "/home/kirjorjos/.steam/debian-installation/steamapps/common/Portal 2"

Killing existing Portal 2 processes, if any

Creating a new portal2_tempcontent directory
Flagging portal2_tempcontent as managed by Spplice

Starting package download from "https://www.p2r3.com/spplice/repo2/reverse/reverse.tar.xz"
Creating directory "scripts/"
Creating directory "scripts/vscripts/"
Writing file "scripts/vscripts/mapspawn.nut"
Creating directory "cfg/"
Writing file "cfg/valve.rc"
Package download and decompression complete

Creating a hard link to _master.cache
Failed to create link, copying instead
```

**Comment by p2r3** [comment]
This is an odd one. ~~You could try starting Spplice as administrator, for starters.~~ Noticed you're on Linux. You could try with `sudo`, but I don't think that'll affect anything.

Odd question, I know, but have you started the base game after installing it? I know sometimes people do just hop to the mod after reinstalling the game, without opening it once without mods. It might fail copying the soundcache simply because there is no soundcache. Try starting up unmodded Portal 2 and running `snd_rebuildaudiocache` in the developer console.

**Comment by kirjorjos** [comment]
Apologies it took me so long to respond.  It completely broke when I tried to run it with sudo, and I had launched and beaten the game even before downloading spplice.  Running `snd_rebuildaudiocache` did work so thank you.
