### ISSUE TITLE
MacOs Glitch version %@

### ISSUE THREAD

**Issue by Loopintohell** [p2r3/spplice#9]
When ever I start the program it pop up a box saying "You can’t use this version of the application “spplice” with this version of macOS. You have macOS %@. The application requires macOS %@ or later."

**Comment by p2r3** [comment]
Unfortunately, this isn't anything we can fix at the moment. This is an issue in Neutralino - the framework that Spplice uses.

For me, macOS compatibility is difficult to support because not only do I not have a macOS system to test on, but I've also got none of the required qualifications to fix issues within the Neutralino framework. Your best bet is opening an issue on [their GitHub](https://github.com/neutralinojs/neutralinojs).
